services:
  torchbearers:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: torchbearers
    ports:
      - "8080:80"
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules/
            - dist/
            - .git/
