name: torchbearers
image: ghcr.io/stevenjhomem/torchbearers:latest
type: web
ports:
  - name: http
    containerPort: 80
    protocol: tcp
healthcheck:
  path: /
  port: 80
  intervalSeconds: 30
  timeoutSeconds: 3
  failureThreshold: 3
resources:
  cpu: 0.25
  memory: 128Mi
restartPolicy: unless-stopped
environment: {}
